### PR TITLE
WIP - Save method

### PR DESCRIPTION
**Pull request by orblivion**
This is a work in progress. I figured that the way in which "save" would make sense in the Python library would be to save the dataframe. Not just generically saving whatever is in `body.csv` like `qri save` does by default.

I handle a few of the flags. I don't know if all of them would apply, but there are more worth adding.

I figured it would be a good time to get opinions though to see if this is what people had in mind.

Based on top of #20

### CODE REVIEW

**Comment by orblivion** [comment]
I'm not sure about the remaining flags. I may need to consult with you on them.

**Comment by dustmop** [comment]
Save in qri is complex for many reasons, and I think we should handle the other PRs before getting around to this one. There's a lot of tricky details to get right. But for now I just wanted to focus on one thing:

> `qri save` on the command line by default saves changes to `body.csv`.

Somewhat of a technically, but just wanted to clarify this, it's related to my comments at https://github.com/qri-io/qri-python/pull/23#issuecomment-685230523. The goal of `qri save` is to write changes to the "qri repository", and files like `body.csv` will only be modified in the case that the dataset has a "working directory", which is not always true. That being said, I think you're doing here is the right thing: serializing the body (which may have been modified in python world), writing it to a tempfile, and passing that to the save command. The last step that `save` takes is to write new contents to the `body.csv` file if it sees that the dataset has a "working directory".

You may want to take a read of this RFC for the future plan regarding the `apply` command and how it related to "save": https://github.com/qri-io/rfcs/blob/master/text/0027-transform_application.md (maybe skip the first part and go straight to "Manual Save") The python library running `save` is actually pretty similar in semantics to how qri `transform` works. You'll also note in that document that `dry-run` is going away, so no need to spend too much energy on it.

Also, naming feedback, I don't think we should go with QriCLIError, since it's possible that this python library is not being used by cli: one major motivation is running it within Jupyter Notebook, or other similar hosted python environments.

**Comment by orblivion** [comment]
To clarify my naming choice: when I made `QriClientError`, it was sort of a reference to `client.py`. Eventually as I moved things around I realized that the errors in question were not all associated with `client.py`, they're associated with the CLI tool. That's why this error specifically has to strip opt the color formatting stuff. So in short, "CLI" doesn't refer to what the user is doing, but rather the tool we are calling out to.

Now that you're consolidating all of this calling out to `loader.py`, would `QriLoaderError` make sense to you?

**Comment by dustmop** [comment]
> Now that you're consolidating all of this calling out to loader.py, would QriLoaderError make sense to you?

I think the question should be, not what source file these are errors in, or how are they implemented, but rather how do they appear to a user of this python package, from their outside perspective. When trying to answer that, something like QriClientError makes sense, since this is a client of the qri command-line application, but maybe there's even better names. Perhaps QriLibError or QriCommandError. I haven't spent a ton of time brain-storming on this, but if there's a change in name it should be focused with that question in mind.

**Pull request closed without merging**
